services:
  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: locallink
      POSTGRES_PASSWORD: locallink
      POSTGRES_DB: locallink
    volumes:
      - locallink_pg:/var/lib/postgresql/data

volumes:
  locallink_pg:


